# Generated by Django 5.0.4 on 2024-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_comment_author_remove_like_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
