# Generated by Django 5.0.4 on 2024-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_assessment_statusrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='gad7_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='phq9_score',
            field=models.IntegerField(null=True),
        ),
    ]
