# Generated by Django 5.0.4 on 2024-05-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_assessment_gad7_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
