# Generated by Django 5.0.4 on 2024-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_statusrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrecord',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
