# Generated by Django 5.0.3 on 2024-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_statusrecord_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusrecord',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions'),
        ),
    ]
