# Generated by Django 5.0.4 on 2024-05-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaTransaction',
            fields=[
                ('id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('payment_title', models.CharField(default='Payment', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='created', max_length=50)),
                ('response_dump', models.JSONField(blank=True, default=dict)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPayment', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapistPayment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
